# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scrollbar_eg1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(389, 279)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(30, 220, 93, 28))
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(150, 220, 93, 28))
        self.btn2.setObjectName("btn2")
        self.mytextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.mytextEdit.setGeometry(QtCore.QRect(20, 20, 331, 191))
        self.mytextEdit.setObjectName("mytextEdit")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(262, 220, 111, 28))
        self.btn3.setObjectName("btn3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scrollbar_eg1"))
        self.btn1.setText(_translate("MainWindow", "No wrap Mode"))
        self.btn2.setText(_translate("MainWindow", "WidgetWidth"))
        self.btn3.setText(_translate("MainWindow", "FixedPixelWidth"))
