# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combobox_eg1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(423, 232)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 70, 261, 31))
        self.comboBox.setObjectName("comboBox")
        self.mylbl1 = QtWidgets.QLabel(self.centralwidget)
        self.mylbl1.setGeometry(QtCore.QRect(100, 30, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mylbl1.setFont(font)
        self.mylbl1.setObjectName("mylbl1")
        self.mylbl2 = QtWidgets.QLabel(self.centralwidget)
        self.mylbl2.setGeometry(QtCore.QRect(30, 130, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mylbl2.setFont(font)
        self.mylbl2.setText("")
        self.mylbl2.setObjectName("mylbl2")
        self.mylbl3 = QtWidgets.QLabel(self.centralwidget)
        self.mylbl3.setGeometry(QtCore.QRect(30, 170, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mylbl3.setFont(font)
        self.mylbl3.setText("")
        self.mylbl3.setObjectName("mylbl3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mylbl1.setText(_translate("MainWindow", "Choose your favorite Fruit:"))
