# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_credential_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(398, 229)
        self.mylbl_username = QtWidgets.QLabel(Form)
        self.mylbl_username.setGeometry(QtCore.QRect(14, 50, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mylbl_username.setFont(font)
        self.mylbl_username.setObjectName("mylbl_username")
        self.mylbl_password = QtWidgets.QLabel(Form)
        self.mylbl_password.setGeometry(QtCore.QRect(14, 120, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mylbl_password.setFont(font)
        self.mylbl_password.setObjectName("mylbl_password")
        self.mybtn_confirm = QtWidgets.QPushButton(Form)
        self.mybtn_confirm.setGeometry(QtCore.QRect(140, 180, 93, 28))
        self.mybtn_confirm.setObjectName("mybtn_confirm")
        self.lineEdit_username = QtWidgets.QLineEdit(Form)
        self.lineEdit_username.setGeometry(QtCore.QRect(210, 50, 161, 22))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(210, 120, 161, 22))
        self.lineEdit_password.setObjectName("lineEdit_password")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "User Credentials App"))
        self.mylbl_username.setText(_translate("Form", "Enter your username:"))
        self.mylbl_password.setText(_translate("Form", "Enter your password:"))
        self.mybtn_confirm.setText(_translate("Form", "Confirm"))
