# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'commandlinkbutton_eg1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 229)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(100, 10, 271, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.clb_btn1 = QtWidgets.QCommandLinkButton(self.frame)
        self.clb_btn1.setGeometry(QtCore.QRect(20, 10, 222, 48))
        self.clb_btn1.setObjectName("clb_btn1")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(420, 10, 281, 151))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.clb_btn2 = QtWidgets.QCommandLinkButton(self.frame_2)
        self.clb_btn2.setGeometry(QtCore.QRect(20, 10, 222, 48))
        self.clb_btn2.setObjectName("clb_btn2")
        self.mylbl2 = QtWidgets.QLabel(self.frame_2)
        self.mylbl2.setGeometry(QtCore.QRect(30, 120, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mylbl2.setFont(font)
        self.mylbl2.setText("")
        self.mylbl2.setObjectName("mylbl2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clb_btn1.setText(_translate("MainWindow", "Click Me :)"))
        self.clb_btn2.setText(_translate("MainWindow", "Increment"))
