# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listWidget_eg1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lw1 = QtWidgets.QListWidget(self.centralwidget)
        self.lw1.setGeometry(QtCore.QRect(20, 100, 541, 271))
        self.lw1.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.lw1.setObjectName("lw1")
        self.lw_Add = QtWidgets.QPushButton(self.centralwidget)
        self.lw_Add.setGeometry(QtCore.QRect(20, 390, 93, 28))
        self.lw_Add.setObjectName("lw_Add")
        self.lw_Count = QtWidgets.QPushButton(self.centralwidget)
        self.lw_Count.setGeometry(QtCore.QRect(140, 390, 93, 28))
        self.lw_Count.setObjectName("lw_Count")
        self.lw_SortAsc = QtWidgets.QPushButton(self.centralwidget)
        self.lw_SortAsc.setGeometry(QtCore.QRect(390, 390, 141, 28))
        self.lw_SortAsc.setObjectName("lw_SortAsc")
        self.lw_Clear = QtWidgets.QPushButton(self.centralwidget)
        self.lw_Clear.setGeometry(QtCore.QRect(270, 390, 93, 28))
        self.lw_Clear.setObjectName("lw_Clear")
        self.lw2 = QtWidgets.QListWidget(self.centralwidget)
        self.lw2.setGeometry(QtCore.QRect(630, 100, 291, 271))
        self.lw2.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.lw2.setObjectName("lw2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 55, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(740, 50, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lw_Toggle = QtWidgets.QPushButton(self.centralwidget)
        self.lw_Toggle.setGeometry(QtCore.QRect(20, 440, 201, 28))
        self.lw_Toggle.setObjectName("lw_Toggle")
        self.lw_SetCurrentItem = QtWidgets.QPushButton(self.centralwidget)
        self.lw_SetCurrentItem.setGeometry(QtCore.QRect(20, 490, 541, 28))
        self.lw_SetCurrentItem.setObjectName("lw_SetCurrentItem")
        self.lw_AddCheckBox = QtWidgets.QPushButton(self.centralwidget)
        self.lw_AddCheckBox.setGeometry(QtCore.QRect(20, 540, 441, 28))
        self.lw_AddCheckBox.setObjectName("lw_AddCheckBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lw_Add.setText(_translate("MainWindow", "Add"))
        self.lw_Count.setText(_translate("MainWindow", "Count"))
        self.lw_SortAsc.setText(_translate("MainWindow", "Sort Ascending Order"))
        self.lw_Clear.setText(_translate("MainWindow", "Clear"))
        self.label.setText(_translate("MainWindow", "List Widget 1"))
        self.label_2.setText(_translate("MainWindow", "List Widget 2"))
        self.lw_Toggle.setText(_translate("MainWindow", "Toggle Alternating RowColors"))
        self.lw_SetCurrentItem.setText(_translate("MainWindow", "Set Current item and Emit Item Selection Changed Signal"))
        self.lw_AddCheckBox.setText(_translate("MainWindow", "Adding checkbox to each Item of List Widget1"))
