# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datetimeedit_eg1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 231)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(80, 60, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.mylbl2 = QtWidgets.QLabel(self.centralwidget)
        self.mylbl2.setGeometry(QtCore.QRect(20, 110, 461, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mylbl2.setFont(font)
        self.mylbl2.setWordWrap(True)
        self.mylbl2.setObjectName("mylbl2")
        self.mybtn = QtWidgets.QPushButton(self.centralwidget)
        self.mybtn.setGeometry(QtCore.QRect(340, 60, 141, 28))
        self.mybtn.setObjectName("mybtn")
        self.mylbl2_2 = QtWidgets.QLabel(self.centralwidget)
        self.mylbl2_2.setGeometry(QtCore.QRect(90, 20, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mylbl2_2.setFont(font)
        self.mylbl2_2.setObjectName("mylbl2_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DateTime_eg1"))
        self.mylbl2.setText(_translate("MainWindow", " "))
        self.mybtn.setText(_translate("MainWindow", "Set Date and Time"))
        self.mylbl2_2.setText(_translate("MainWindow", "Edit the Date and Time:"))
