# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fontcombobox_eg1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(375, 194)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fontComboBox = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox.setGeometry(QtCore.QRect(60, 60, 226, 22))
        self.fontComboBox.setObjectName("fontComboBox")
        self.mylb2 = QtWidgets.QLabel(self.centralwidget)
        self.mylb2.setGeometry(QtCore.QRect(30, 120, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mylb2.setFont(font)
        self.mylb2.setText("")
        self.mylb2.setObjectName("mylb2")
        self.mylbl1 = QtWidgets.QLabel(self.centralwidget)
        self.mylbl1.setGeometry(QtCore.QRect(70, 20, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mylbl1.setFont(font)
        self.mylbl1.setObjectName("mylbl1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mylbl1.setText(_translate("MainWindow", "Select the Font Family :"))
