# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkbutton_eg1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(502, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 90, 331, 251))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl1 = QtWidgets.QLabel(self.frame)
        self.lbl1.setGeometry(QtCore.QRect(40, 200, 251, 20))
        self.lbl1.setText("")
        self.lbl1.setObjectName("lbl1")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 251, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chk_Apple = QtWidgets.QCheckBox(self.layoutWidget)
        self.chk_Apple.setChecked(False)
        self.chk_Apple.setObjectName("chk_Apple")
        self.verticalLayout.addWidget(self.chk_Apple)
        self.chk_Orange = QtWidgets.QCheckBox(self.layoutWidget)
        self.chk_Orange.setObjectName("chk_Orange")
        self.verticalLayout.addWidget(self.chk_Orange)
        self.chk_Banana = QtWidgets.QCheckBox(self.layoutWidget)
        self.chk_Banana.setObjectName("chk_Banana")
        self.verticalLayout.addWidget(self.chk_Banana)
        self.chk_Pear = QtWidgets.QCheckBox(self.layoutWidget)
        self.chk_Pear.setObjectName("chk_Pear")
        self.verticalLayout.addWidget(self.chk_Pear)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 391, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chk_Apple.setText(_translate("MainWindow", "Apple"))
        self.chk_Orange.setText(_translate("MainWindow", "Orange"))
        self.chk_Banana.setText(_translate("MainWindow", "Banana"))
        self.chk_Pear.setText(_translate("MainWindow", "Pear"))
        self.label.setText(_translate("MainWindow", "You can choose more than one fruit from the options:"))
