# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MouseEvents_Eg1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MouseEvents_Eg1(object):
    def setupUi(self, MouseEvents_Eg1):
        MouseEvents_Eg1.setObjectName("MouseEvents_Eg1")
        MouseEvents_Eg1.resize(407, 197)
        self.centralwidget = QtWidgets.QWidget(MouseEvents_Eg1)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 20, 270, 116))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lm_click_btn_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.lm_click_btn_2.setObjectName("lm_click_btn_2")
        self.horizontalLayout_3.addWidget(self.lm_click_btn_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.hover_mouse_btn_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.hover_mouse_btn_2.setObjectName("hover_mouse_btn_2")
        self.horizontalLayout_3.addWidget(self.hover_mouse_btn_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rm_click_btn_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.rm_click_btn_2.setObjectName("rm_click_btn_2")
        self.horizontalLayout_4.addWidget(self.rm_click_btn_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.left_double_click_btn_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.left_double_click_btn_2.setObjectName("left_double_click_btn_2")
        self.horizontalLayout_4.addWidget(self.left_double_click_btn_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        MouseEvents_Eg1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MouseEvents_Eg1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 407, 26))
        self.menubar.setObjectName("menubar")
        MouseEvents_Eg1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MouseEvents_Eg1)
        self.statusbar.setObjectName("statusbar")
        MouseEvents_Eg1.setStatusBar(self.statusbar)

        self.retranslateUi(MouseEvents_Eg1)
        QtCore.QMetaObject.connectSlotsByName(MouseEvents_Eg1)

    def retranslateUi(self, MouseEvents_Eg1):
        _translate = QtCore.QCoreApplication.translate
        MouseEvents_Eg1.setWindowTitle(_translate("MouseEvents_Eg1", "MouseEvents_Eg1"))
        self.lm_click_btn_2.setText(_translate("MouseEvents_Eg1", "Left Mouse click"))
        self.hover_mouse_btn_2.setText(_translate("MouseEvents_Eg1", "Mouse Hover"))
        self.rm_click_btn_2.setText(_translate("MouseEvents_Eg1", "Right Mouse click"))
        self.left_double_click_btn_2.setText(_translate("MouseEvents_Eg1", "Left Double click "))
